### ISSUE TITLE
This is actually included in the vendor folder now, but it is not working for me.

### ISSUE THREAD

**Issue by Jieiku** [pawankparmar/failedlogin#1]
So at first I installed this https://magento.stackexchange.com/questions/316913/magento-2-module-to-log-failed-login-attempts-for-fail2ban

but then the website says already loaded, so then i look for it and i see it is in the vendors folder.

so I removed the one I downloaded and then just went to my web root where magento is installed and did:
```
cd /var/www/magento2/
composer require pawan/failedlogin
```
the process completed successfully but the invalid login attempts do not appear to be getting logged, what should I be looking for to debug why it might not be working?

**Comment by dvershinin** [comment]
Have you run `php ./bin/magento module:enable Pawan_FailedLogin` ?

**Comment by Jieiku** [comment]
No I have not, going to try that now, thanks so much for the help.

**Comment by Jieiku** [comment]
That command enabled the plugin, I did not even realize I had to do that. It still does not seem to be logging to any files the bad login attempts, which file does it log to?

sudo -u www-data php bin/magento module:enable Pawan_FailedLogin
sudo -u www-data php bin/magento setup:upgrade
sudo -u www-data php bin/magento setup:di:compile

**Comment by dvershinin** [comment]
Apparently, your website files are owned by `www-data` user, so installing this module is your least concern.
Your setup is very insecure. Have a look at the [basics of proper permission setup in PHP-FPM / NGINX stack](https://www.getpagespeed.com/server-setup/nginx-and-php-fpm-what-my-permissions-should-be).

**Comment by Jieiku** [comment]
eeeek, I had no idea that files being owned by www-data was a bad thing, I was under the assumption that is how it is supposed to be.

What exactly is the problem with the files being owned by www-data?

your article says: Do not use www-data or nginx as website user. This is wrong and will lead to more troubles! but it does not give an example why it is wrong, and so I do not learn anything, all I could do is follow what your saying. but an example of why its bad would be helpful.

EDIT: Additionally in my case the install is a single website (magento is installed to an unprivileged LXC container), one possible cause for concern I could think of is if the machine were hosting more than one site. but my machine/container is not.

**Comment by Jieiku** [comment]
I am hoping your just too busy to respond because if there is a good reason for web site files not being owned by www-data in an LXC container then I absolutely need and want to know about it. I have several web services and this is how they have been setup based on lots of documentation that says to do exactly what I have done.

Appreciate your help, thanks again.

https://linuxize.com/post/how-to-set-up-nginx-server-blocks-on-ubuntu-20-04/

`sudo chown -R www-data: /var/www/domain1.com`

**Comment by pawan** [comment]
@xekon 
You need to run basic command after **composer require pawan/failedlogin** like:

- php bin/magento setup:upgrade
- php bin/magento c:f 

You can verify module is correct installed by **php bin/magento module:status**

if module is correctly installed, it will log failed admin attempt at var/log/failedlogin.log

**Comment by Jieiku** [comment]
The Status command does list Pawan_FailedLogin but it is not being logged to the file you mention, that file is not even being created. I tried to create the file and chmod 777 incase it was just an issue of permissions but it still does not get written to.

edit: I did run the commands you list above.

**Comment by pawan** [comment]
what exact version of magento you are using ?

**Comment by Jieiku** [comment]
sudo -u www-data php bin/magento --version
Magento CLI 2.4.1

php7.4
mariadb-10.4
composer 1.10.17

**Comment by Jieiku** [comment]
@pawan what is the latest version of Magento that is confirmed working with this plugin?

**Comment by pawan** [comment]
@xekon 
I just installed it on magento CE 2.4.1 and it is working fine!

**Comment by pawan** [comment]
@xekon 
As per you it is included in vendor folder, let me know module name and it is logging failed attempt in database Or file ?

**Comment by Jieiku** [comment]
looks like it should be going to /var/log/failedlogin.log
I may try reinstalling magento, im still in development phase and don't have any customization done yet.

`cat /var/www/magento/vendor/pawan/failedlogin/Logger/Handler.php`

```
<?php

namespace Pawan\FailedLogin\Logger;

use \Monolog\Logger;
use \Magento\Framework\Logger\Handler\Base;

class Handler extends Base
{
    /**
     * Logging Level
     * @var int
     */
    public $loggerType = Logger::INFO;

    /**
     * File Name
     * @var string
     */
    public $fileName = '/var/log/failedlogin.log';
}
```

**Comment by pawan** [comment]
Yes @xekon , I mentioned in my comment https://github.com/pawan/failedlogin/issues/1#issuecomment-738859827
Just try on local installation, I should work smoothly!

**Comment by Jieiku** [comment]
@pawan I tried to do a local install instead, but I am thinking the one in the vendor folder is somehow messing it up, I even tried deleting the folder and all contents (`sudo rm -rf /var/www/magento/vendor/pawan`). after installing magento I did this to install locally:

```
sudo su magento
cd /var/www/magento
mkdir -p /var/www/magento/app/code/pawan
cd /var/www/magento/app/code/pawan
git clone https://github.com/pawan/failedlogin
exit
cd /var/www/magento
sudo -u www-data php bin/magento module:enable Pawan_FailedLogin
sudo -u www-data php bin/magento setup:upgrade
sudo -u www-data php bin/magento c:f
sudo -u www-data php bin/magento module:status
```
and it list the module as installed, but when I purposely try logging into admin panel with bad password I get this stack trace:

```
1 exception(s):
 Exception #0 (ReflectionException): Class Pawan\FailedLogin\Observer\FailedLogin does not exist
```

**Comment by Jieiku** [comment]
Ok I got it installed with the "local" copy, and resolved the class not found error by making sure that the case of the letters (capitalization) was correct, because it was quite literally not finding it, I also renamed the module so that it would not conflict with the one included in the vendor folder.

Unfortunately this one is behaving just like the one in the vendor folder did for me originally, it says the module is active, there are no errors, but when you intentionally put a bad login info into the login page, it never gets logged to file, and the file never gets created.

```
sudo su magento
cd /var/www/magento
mkdir -p /var/www/magento/app/code/PawanLocal
cd /var/www/magento/app/code/PawanLocal
git clone https://github.com/pawan/failedlogin FailedLogin

grep -i --binary-files=without-match --include=\* -rnw '/var/www/magento/app/code/PawanLocal/FailedLogin' -e ".*awan.*"
find /var/www/magento/app/code/PawanLocal/FailedLogin \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/.awan/PawanLocal/g'
find /var/www/magento/app/code/PawanLocal/FailedLogin \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/failedlogin/FailedLogin/g'
grep -i --binary-files=without-match --include=\* -rnw '/var/www/magento/app/code/PawanLocal/FailedLogin' -e ".*awan.*"

exit
cd /var/www/magento
sudo -u www-data php bin/magento module:enable PawanLocal_FailedLogin
sudo -u www-data php bin/magento setup:upgrade
sudo -u www-data php bin/magento c:f
sudo -u www-data php bin/magento setup:di:compile
sudo -u www-data php bin/magento module:status
```

**Comment by Jieiku** [comment]
Oh my. Well, I feel sheepish.

`public $fileName = '/var/log/failedlogin.log';`

I did not realize that was a relative path, I was literrally looking `/var/log` on my system, not `/var/www/magento/var/log`

Thank you for taking the time to help @pawan and @dvershinin 

I am going to rollback my container and install using the one included in vendor folder because it was probably working perfectly fine, I just was not looking in the correct place.

**Comment by Jieiku** [comment]
Yep, the one in repository works fine, Installed like this:
```
sudo su magento
cd /var/www/magento
composer require pawan/failedlogin
exit
cd /var/www/magento
sudo -u www-data php bin/magento module:enable Pawan_FailedLogin --clear-static-content
sudo -u www-data php bin/magento setup:upgrade
sudo -u www-data php bin/magento c:f
sudo -u www-data php bin/magento setup:di:compile
sudo -u www-data php bin/magento module:status
```
additionally here is the setup for fail2ban jail:
`sudo apt install fail2ban`
`sudo nano /etc/fail2ban/filter.d/magento.conf`
```
[Definition]
failregex = .*INFO: <HOST> \[\] \[\]$
ignoreregex =
```

`sudo nano /etc/fail2ban/jail.local`
```
[magento]
enabled = true
filter = magento
action = iptables-allports
logpath = /var/www/magento/var/log/failedlogin.log
maxretry = 1
```

**Comment by pawan** [comment]
@xekon glad to know it worked
I think it was working from first install and you were just looking into wrong path!
